### ISSUE TITLE
RSSBOT

### ISSUE THREAD

**Issue by huxcrux** [SmBe19/RedditBots#3]
Traceback (most recent call last):
  File "/usr/lib/python3.4/configparser.py", line 824, in items
    d.update(self._sections[section])
KeyError: 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RSSBot.py", line 125, in <module>
    run_bot()
  File "RSSBot.py", line 76, in run_bot
    o = OAuth2Util.OAuth2Util(r)
  File "/home/bl0m1/bot/RedditBots-master/RSSBot/OAuth2Util.py", line 162, in **init**
    self.refresh()
  File "/home/bl0m1/bot/RedditBots-master/RSSBot/OAuth2Util.py", line 334, in refresh
    self._check_token_present()
  File "/home/bl0m1/bot/RedditBots-master/RSSBot/OAuth2Util.py", line 282, in _check_token_present
    options = self.config.items(CONFIGKEY_TOKEN[0])
  File "/usr/lib/python3.4/configparser.py", line 827, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'token'

**Comment by SmBe19** [comment]
OAuth2Util changed the format of the config file. I'll update someday the template, as of now just look up the new config format [here](https://github.com/SmBe19/praw-OAuth2Util/blob/master/OAuth2Util/README.md).

**Comment by huxcrux** [comment]
TY, ill try my best to fix it myself, can you fix it in a week?

**Comment by SmBe19** [comment]
Will probably take longer, have other projects atm.

**Comment by SmBe19** [comment]
I just updated the oauth templates, if you still want to use my bot, please try again. Sorry it took so long.
