### ISSUE TITLE
OAuth2 Still not working on pythoneverywhere

### ISSUE THREAD

**Issue by Syndrogo** [SmBe19/RedditBots#5]
`python3.5 ~/WIKI/UserListKeeper.py
:0: UserWarning: The keyword`bot`in your user_agent may be problematic.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/praw/internal.py", line 213, in _raise_response_exceptions
    response.raise_for_status()  # These should all be directly mapped
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.reddit.com/api/v1/access_token/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/Syndrogo/.local/lib/python3.5/site-packages/OAuth2Util/OAuth2Util.py", line 345, in refresh
    new_token = self.r.refresh_access_information(self._get_value(CONFIGKEY_REFRESH_TOKEN))
  File "/usr/local/lib/python3.5/dist-packages/praw/__init__.py", line 1492, in refresh_access_information
    refresh_token=refresh_token or self.refresh_token)
  File "<decorator-gen-11>", line 2, in refresh_access_information
  File "/usr/local/lib/python3.5/dist-packages/praw/decorators.py", line 288, in require_oauth
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/praw/__init__.py", line 735, in refresh_access_information
    retval = self._handle_oauth_request(data)
  File "/usr/local/lib/python3.5/dist-packages/praw/__init__.py", line 659, in _handle_oauth_request
    response = self._request(url, auth=auth, data=data, raw_response=True)
  File "/usr/local/lib/python3.5/dist-packages/praw/__init__.py", line 454, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python3.5/dist-packages/praw/internal.py", line 215, in _raise_response_exceptions
    raise HTTPException(_raw=exc.response)
praw.errors.HTTPException: HTTP error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/Syndrogo/WIKI/UserListKeeper.py", line 228, in <module>
    run_bot()
  File "/home/Syndrogo/WIKI/UserListKeeper.py", line 190, in run_bot
    o = OAuth2Util.OAuth2Util(r)
  File "/home/Syndrogo/.local/lib/python3.5/site-packages/OAuth2Util/OAuth2Util.py", line 157, in __init__
    self.refresh()
  File "/home/Syndrogo/.local/lib/python3.5/site-packages/OAuth2Util/OAuth2Util.py", line 356, in refresh
    self._get_new_access_information()
  File "/home/Syndrogo/.local/lib/python3.5/site-packages/OAuth2Util/OAuth2Util.py", line 254, in _get_new_access_information
    self._start_webserver(url)
  File "/home/Syndrogo/.local/lib/python3.5/site-packages/OAuth2Util/OAuth2Util.py", line 227, in _start_webserver
    self.server = HTTPServer(server_address, OAuth2UtilRequestHandler)
  File "/usr/lib/python3.5/socketserver.py", line 443, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 457, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address`

**Comment by SmBe19** [comment]
Can you please post your `ouath.ini` file (without secrets).

**Comment by Syndrogo** [comment]
```
[app]
# These grant the bot to every scope, only use those you want it to access.
scope=identity,account,edit,flair,history,livemanage,modconfig,modflair,modlog,modothers,modposts,modself,modwiki,mysubreddits,privatemessages,read,report,save,submit,subscribe,vote,wikiedit,wikiread
refreshable=True
app_key=qL9eNJHCKz0sWg
app_secret=

[server]
server_mode=False
url=proxy.server
port=3128
redirect_path=authorize_callback
link_path=oauth

# Will be filled automatically
[token]
token=None
refresh_token=None
valid_until=0
```

I have tried both with and without the server

**Comment by SmBe19** [comment]
A few things you can check:
- Does `proxy.server` resolve to the computer the bot is running on (normally localhost)?
- Did you enter the correct redirect uri in the reddit settings (in your case `http://proxy.server:3128/authorize_callback`)
- Is the port `3128` already in use by another process?

**Comment by Syndrogo** [comment]
proxy.server is based off python everywhere link to access the internet from a script
the app is set to the right call back
andyes im running another bot (rssbot but its working off another system for the server) Also sent me the old Auth and it works for that bot.

**Comment by Syndrogo** [comment]
bump

**Comment by SmBe19** [comment]
As far as I see the problem doesn't lie with OAuth2Util but with your settings.

According to [this link](https://help.pythonanywhere.com/pages/403ForbiddenError/) `proxy.server` is only the proxy server used for whitelisting certain pages. You can't reach the script using this url. You can try setting the url to `yourusername.pythonanywhere.com` and port to `80`. But I don't know enough about how python anywhere works to help you there.

As you can't open a web browser on python anywhere you should use `server_mode = True`.

If you don't manage to run it, you can use an old version of the bot that used username / password authentication.
